apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8s-microproject
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  #Conserve les données après suppression
  storageClassName: manual
  hostPath:
    path: "/data"
