apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8s-microproject
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  #Conserve les données après suppression
  hostPath:
    path: "/data"
