apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8s-microproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: pv-k8s-microproject

