apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8s-microproject
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


